// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3TNGUI5nnXsrIdDd9ZPopHShjLDl3oJw',
    appId: '1:735323458742:web:0d117132770008cc0fea17',
    messagingSenderId: '735323458742',
    projectId: 'booklist-c55f1',
    authDomain: 'booklist-c55f1.firebaseapp.com',
    storageBucket: 'booklist-c55f1.firebasestorage.app',
    measurementId: 'G-JVMYNKLLQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzCsQMv6ERwjE43xzd4gk2FJ-WIZHVEqY',
    appId: '1:735323458742:android:705ef37b9a14c41e0fea17',
    messagingSenderId: '735323458742',
    projectId: 'booklist-c55f1',
    storageBucket: 'booklist-c55f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXgr2HcG56AR9dNNOTnHKxv_7QRY9D02c',
    appId: '1:735323458742:ios:eea987eac3357b2b0fea17',
    messagingSenderId: '735323458742',
    projectId: 'booklist-c55f1',
    storageBucket: 'booklist-c55f1.firebasestorage.app',
    iosBundleId: 'com.example.booklist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXgr2HcG56AR9dNNOTnHKxv_7QRY9D02c',
    appId: '1:735323458742:ios:eea987eac3357b2b0fea17',
    messagingSenderId: '735323458742',
    projectId: 'booklist-c55f1',
    storageBucket: 'booklist-c55f1.firebasestorage.app',
    iosBundleId: 'com.example.booklist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3TNGUI5nnXsrIdDd9ZPopHShjLDl3oJw',
    appId: '1:735323458742:web:4de86eec7413beb10fea17',
    messagingSenderId: '735323458742',
    projectId: 'booklist-c55f1',
    authDomain: 'booklist-c55f1.firebaseapp.com',
    storageBucket: 'booklist-c55f1.firebasestorage.app',
    measurementId: 'G-4QBSW7MBGP',
  );
}
